### ISSUE TITLE
Doesn't seem to contain all info

### ISSUE THREAD

**Issue by AndyRPH** [happyleavesaoc/python-motorparts#3]
My Uconnect app shows me charge status/level for my Pacifica plug in hybrid.  Can this be updated to also return that data?

**Comment by happyleavesaoc** [comment]
Maybe, but I don't own a hybrid so I can't say for sure. Also not willing to buy one just to add this feature ;)

**Comment by AndyRPH** [comment]
I'm happy to provide the raw data my login returns if there is some
instructions to execute the request/response via command line, or log that
holds it or such.  I'm running it via hass.io on a pi3b+.



On Dec 30, 2018, at 10:27 AM, happyleavesaoc <notifications@github.com>
wrote:

Maybe, but I don't own a hybrid so I can't say for sure. Also not willing
to buy one just to add this feature ;)

—

**Comment by AndyRPH** [comment]
Turns out the app shows charge status and a whole lot more data than the website, which has nothing PHEV specific.  Closing, as I don't see anyone's attempted to pull the data the same way the app does.
